### ISSUE TITLE
ESP32 не компилируется 

### ISSUE THREAD

**Issue by AVG-N** [ssilver2007/LCD_1602_RUS_ALL#2]
Доброго времени суток!
Библиотека не работает под ESP32 ?
Попытался скомпилировать пример HelloWorld_I2C.ino,
выводит ошибку:
\Arduino\libraries\LCD_1602_RUS_ALL-master\examples\HelloWorld_I2C\HelloWorld_I2C.ino:6:0:
\Arduino\libraries\LCD_1602_RUS_ALL-master/LCD_1602_RUS_ALL.h:16:26: fatal error: avr/pgmspace.h: No such file or directory

compilation terminated.

Используем библиотеку LCD_1602_RUS_ALL-master версии 1.1.1 из папки: D:\User\Мои документы\Arduino\libraries\LCD_1602_RUS_ALL-master
exit status 1
Ошибка компиляции для платы ESP32 Dev Module.

**Comment by ssilver2007** [comment]
Проверьте правильность указания путей к библиотекам для Arduino IDE.
Компилятор не находит стандартную библиотеку  avr/pgmspace.h

вт, 7 янв. 2020 г. в 19:38, AVG-N <notifications@github.com>:

**Comment by AVG-N** [comment]
Спасибо! действительно отсутствовала папка . Сделал паку avr закинул pgmspace.h - работает.
