### ISSUE TITLE
Теперь не можно

### ISSUE THREAD

**Issue by Ilushock** [ssilver2007/LCD_1602_RUS_ALL#4]
Приветствую!
Сразу говорю, что я пишу свою первую программку для Ардуино, Поэтому вопрос может показаться тупым. Мне он таким не кажется, поэтому и задаю :)
Итак имею Win7 32, Arduino 1.8.5, заливаю HelloWorld.ino в китайскую ардуину. При первом запуске пишет: "Теперь можно по-русски". Ну и прекрасно, сказал я, и поправил значение переменной. На экран вывелись кракозябры во всех строках. Поправил значение только функции lcd.print опять та же фигня. 
Что-то с кодировкой? Куда смотреть, где править?

**Comment by ssilver2007** [comment]
Пример HelloWorld.ino из старой версии библиотеки. Поставьте новую библиотеку LCD_1602_RUS_ALL и попробуйте с новыми примерами. Теперь примеры поделены на два типа - подключение по I2C и 10-контактное.

**Comment by Ilushock** [comment]
> Поставьте новую библиотеку LCD_1602_RUS_ALL

Не сильно помогло При первом запуске всё отлично, всё по-русски. НО. Как только что-то поменяю, опять опа. Только теперь кракозябры заменились на "RRR"

**Comment by ssilver2007** [comment]
Русские буквы в тексте скетча на экране монитора отображаются нормально? А когда текст меняете на свой? На мониторе все нормально, а на дисплее снова кракозябры?

**Comment by Ilushock** [comment]
В скетче нормально. Когда текст меняю на свой - тоже нормально. В мониторе компьютера тоже всё понятно, только как что-нибудь поменяю - в ардуине трындец.
До замены чего-либо:
![IMG_20200217_223858_1](https://user-images.githubusercontent.com/34733861/74679547-36f00080-51cf-11ea-9951-2e6ab193add2.jpg)
После замены "язык" на "Я"
![IMG_20200217_223944_1](https://user-images.githubusercontent.com/34733861/74679570-496a3a00-51cf-11ea-9333-1ccdf07bb2cc.jpg)

Я вот даже попробовал просто удалить несколько символов в слове "язык", оставил только букву "я". И опять фигня получается.
Очень подозреваю, что с кодировкой проблемы. Но где смотреть не пойму.

**Comment by ssilver2007** [comment]
При сохранении скетча, видимо, меняется кодировка. Попробуйте поставить 1.8.10, у меня сейчас такая и проблем с кодировкой нет. На 1.8.5 не помню, возможно не пробовал.
