### ISSUE TITLE
no matching function for call to 'LCD_1602_RUS<LiquidCrystal>::print(long int)'

### ISSUE THREAD

**Issue by ghost** [ssilver2007/LCD_1602_RUS_ALL#5]
//#include <LiquidCrystal.h>
#define _LCD_TYPE 2
#include "LCD_1602_RUS\LCD_1602_RUS_ALL.h"
#include <DHT.h>
LCD_1602_RUS <LiquidCrystal> lcd(7, 6, 5, 4, 3, 2); // (RS, E, DB4, DB5, DB6, DB7)
#define DHTPIN 10

DHT dht(DHTPIN, DHT22);
void setup() {
  Serial.begin(9600);
  dht.begin();
  lcd.begin(16, 2);
}

void loop() {
  float t = dht.readTemperature();
  float h = dht.readHumidity();
  if (isnan(h) || isnan(t)) {
  
    lcd.setCursor(0, 0);              // Устанавливаем курсор в начало 1 строки
    lcd.print("Error read DHT22");       // Выводим текст
    return;
  }
    //Serial.println("Не удается считать показания");
  
  lcd.setCursor(0, 0);              // Устанавливаем курсор в начало 1 строки
  lcd.print("Тем-ра: ");       // Выводим текст
  lcd.print(round(t));
  lcd.print(" *C");
  lcd.setCursor(0, 1);              // Устанавливаем курсор в начало 2 строки
  lcd.print("Влажность: ");       // Выводим текст
  //lcd.print(round(h));       // Выводим текст
  lcd.print(" %");       // Выводим текст
  delay(100);

**Comment by ssilver2007** [comment]
Исправлено. Пробуйте.

**Comment by greeg38** [comment]
no matching function for call to 'LCD_1602_RUS::print(bool&)'

`#define _LCD_TYPE 1  // для работы с I2C дисплеями
#include <LCD_1602_RUS_ALL.h>
LCD_1602_RUS lcd(0x27, 16, 2);
bool td=1;
void setup() {
  lcd.init();
  lcd.backlight();
  lcd.setCursor(0, 0);
  lcd.print("Привет!");
  lcd.print("hello!");
  lcd.print(td);
}

void loop() {
}`

**Comment by ssilver2007** [comment]
Здравствуйте.
Напрямую никак. Надо сначала сформировать текстовую строку через sprinf, а
затем ее вывести через print.

вт, 11 окт. 2022 г., 6:02 greeg38 ***@***.***>:
