### ISSUE TITLE
Ошибка после вывода 8-го уникального кириллического символа 

### ISSUE THREAD

**Issue by vidiker** [ssilver2007/LCD_1602_RUS_ALL#6]
Здравствуйте.
Похоже, после вывода 8-го уникального кириллического символа нельзя вывести никакой из предыдущих 7-ми без затирания ячеек.
пример кода с ошибкой:

`#define _LCD_TYPE 2
#include <LCD_1602_RUS_ALL.h>

LCD_1602_RUS <LiquidCrystal> lcd(/*rs*/ 8, /*en*/ 9, /*d4*/ 4, /*d5*/ 5, /*d6*/ 6, /*d7*/ 7); //For LCD Keypad Shield

void setup() {

  lcd.begin(16, 2);

}

void loop() {

  lcd.setCursor(0, 0); lcd.print("Игральная кость1"); // Ошибочно отображается "ьгральная кость1"
  delay(1000);

  // обход ошибки
  lcd.setCursor(0, 0); lcd.print("Игральная кос ь2");
  lcd.setCursor(13, 0); lcd.print("т");
  delay(1000);

}`

**Comment by ssilver2007** [comment]
Да, есть такая ошибка. Исправил. Скачайте текущую версию библиотеки. Изменения коснулись файла LCD_1602_RUS_ALL.h

**Comment by vidiker** [comment]
Спасибо, помогло.
